/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTAS;

import CONTROLADOR.Butaca_BD;
import CONTROLADOR.Funcion_BD;
import CONTROLADOR.Pelicula_BD;
import CONTROLADOR.Sala_BD;
import MODELO.Butaca;
import MODELO.Conexion;
import MODELO.Funcion;
import MODELO.Pelicula;
import MODELO.Sala;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thomas
 */
public class VistaFuncion extends javax.swing.JInternalFrame {
    private Funcion_BD  funcion_bd;
    private Conexion conexion;
    private DefaultTableModel modelo;
    private ArrayList<Pelicula> listaPelicula;
    private Pelicula_BD pelicula_bd;
    private ArrayList<Sala> listaSala;
    private Sala_BD sala_bd;
    private ArrayList<Butaca> listaButaca;
    private Butaca_BD butaca_bd;
    private ArrayList<Funcion> listaFuncion;
    private DefaultTableModel modelo1;
    private DefaultTableModel modelo2;
    private DefaultTableModel modelo3;

    
    

    /**
     * Creates new form VistaFuncion
     */
    public VistaFuncion() {
        initComponents();
        conexion = new Conexion("jdbc:mysql://localhost/proyecto_cine", "root", "");
        funcion_bd = new Funcion_BD(conexion);
        modelo= new DefaultTableModel();
        modelo1= new DefaultTableModel();
        modelo2=new DefaultTableModel();
        modelo3=new DefaultTableModel();

          
        pelicula_bd = new Pelicula_BD(conexion);
        listaPelicula=(ArrayList)pelicula_bd.obtenerListaPelicula();
        
        sala_bd = new Sala_BD(conexion);
        listaSala=(ArrayList)sala_bd.obtenerListaSala();
        
        butaca_bd = new Butaca_BD(conexion);
        listaButaca=(ArrayList)butaca_bd.obtenerListaButaca();
        
        funcion_bd = new Funcion_BD(conexion);
        listaFuncion=(ArrayList)funcion_bd.obtenerListaFuncion();
        
        cargarpelicula();
        cargarsala();
        cargarbutaca();
        
        
        CabeceraTablaPelicula();
        CargarDatosPelicula();
        CabeceraTablaSala();
        CargarDatosSala();
        CabeceraTablaButaca();
        CargarDatosButaca();
        CabeceraTablaFuncion();
        CargarDatosFuncion();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtId = new javax.swing.JTextField();
        jtId_pelicula = new javax.swing.JTextField();
        jtId_sala = new javax.swing.JTextField();
        btGuardar = new javax.swing.JButton();
        btBorrar = new javax.swing.JButton();
        btActualizar = new javax.swing.JButton();
        btLimpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtId_butaca = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtFecha = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtHora_entrada = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtHora_salida = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jCBId_sala = new javax.swing.JComboBox<>();
        jCBId_butaca = new javax.swing.JComboBox<>();
        jCBId_pelicula = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tPelicula = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        tSala = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        tButaca = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        tFuncion = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("ID_PELICULA:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("ID_SALA:");

        btGuardar.setText("Guardar");
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });

        btBorrar.setText("Borrar");
        btBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBorrarActionPerformed(evt);
            }
        });

        btActualizar.setText("Actualizar");
        btActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActualizarActionPerformed(evt);
            }
        });

        btLimpiar.setText("Limpiar");
        btLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpiarActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("FUNCION");

        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("ID:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("ID_BUTACA:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("FECHA:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("HORARIO_ENTRADA:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("HORARIO_SALIDA:");

        jLabel5.setText("AAAA-MM-DD");

        jLabel6.setText("HH:MM:SS");

        jLabel8.setText("HH:MM:SS");

        jLabel13.setText("LISTA DE PELICULA");

        jLabel14.setText("LISTA DE BUTACAS");

        jLabel15.setText("LISTA DE SALA");

        tPelicula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(tPelicula);

        tSala.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(tSala);

        tButaca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(tButaca);

        jLabel16.setText("LISTA DE FUNCIONES ");

        tFuncion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane9.setViewportView(tFuncion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel15)
                        .addGap(360, 360, 360)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel13))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel14))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(98, 98, 98))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(35, 35, 35)
                                        .addComponent(jtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(35, 35, 35)
                                        .addComponent(jtHora_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(35, 35, 35)
                                        .addComponent(jtHora_salida, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(34, 34, 34)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtId_pelicula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addGap(123, 123, 123))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtId_sala, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(35, 35, 35)
                                        .addComponent(jtId_butaca, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel8)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(btBuscar))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jCBId_pelicula, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jCBId_sala, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jCBId_butaca, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(133, 133, 133))
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btGuardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btBorrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btActualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btLimpiar)))
                        .addGap(48, 48, 48))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addComponent(btBuscar, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtId_pelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jCBId_pelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jtId_sala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCBId_sala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jtId_butaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCBId_butaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(jtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(jtHora_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(jtHora_salida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btGuardar)
                            .addComponent(btBorrar)
                            .addComponent(btActualizar)
                            .addComponent(btLimpiar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 117, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
        
        //tomardatos();

        Pelicula pelicula= new Pelicula();
        int  id_pelicula = Integer.parseInt(jtId_pelicula.getText());
        pelicula.setId_pelicula(id_pelicula);
        
        Sala sala= new Sala();
        int  id_sala = Integer.parseInt(jtId_sala.getText());
        sala.setId_sala(id_sala);
        
        Butaca butaca= new Butaca();
        int  id_butaca = Integer.parseInt(jtId_butaca.getText());
        butaca.setId_butaca(id_butaca);
        
        String fecha= jtFecha.getText();
        String hora_entrada= jtHora_entrada.getText();
        String hora_salida= jtHora_salida.getText();
        Funcion funcion = new Funcion(pelicula,sala,butaca,fecha,hora_entrada,hora_salida);
        funcion_bd.guardarFuncion(funcion);
        jtId.setText(funcion.getId_funcion()+"");
    }//GEN-LAST:event_btGuardarActionPerformed

    private void btBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBorrarActionPerformed
        int id = Integer.parseInt(jtId.getText());
        funcion_bd.borrarFuncion(id);
    }//GEN-LAST:event_btBorrarActionPerformed

    private void btActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActualizarActionPerformed

        if(jtId.getText()!= null){
            Pelicula pelicula= new Pelicula();
            int  id_pelicula = Integer.parseInt(jtId_pelicula.getText());
            pelicula.setId_pelicula(id_pelicula);

            Sala sala= new Sala();
            int  id_sala = Integer.parseInt(jtId_sala.getText());
            sala.setId_sala(id_sala);

            Butaca butaca= new Butaca();
            int  id_butaca = Integer.parseInt(jtId_butaca.getText());
            butaca.setId_butaca(id_butaca);

            String fecha= jtFecha.getText();
            String hora_entrada= jtHora_entrada.getText();
            String hora_salida= jtHora_salida.getText();
            
            Funcion funcion = new Funcion();
            funcion.setId_funcion(Integer.parseInt(jtId.getText()));
            funcion.setId_pelicula(pelicula);
            funcion.setId_sala(sala);
            funcion.setId_butaca(butaca);
            funcion.setFecha(fecha);
            funcion.setHora_entrada(hora_entrada);
            funcion.setHora_salida(hora_salida);
            funcion_bd.modificarFuncion(funcion);
            
        }

    }//GEN-LAST:event_btActualizarActionPerformed

    private void btLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpiarActionPerformed
        jtId.setText("");
        jtId_pelicula.setText("");
        jtId_sala.setText("");
        jtId_butaca.setText("");
        jtFecha.setText("");
        jtHora_entrada.setText("");
        jtHora_salida.setText("");
    }//GEN-LAST:event_btLimpiarActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        int id = Integer.parseInt(jtId.getText());
        Funcion funcion = funcion_bd.buscarFuncion(id);
        if(funcion!= null){
            jtId.setText(String.valueOf(funcion.getId_funcion()));
            jtId_pelicula.setText(String.valueOf(funcion.getId_pelicula().getId_pelicula()));
            jtId_sala.setText(String.valueOf(funcion.getId_sala().getId_sala()));
            jtId_butaca.setText(String.valueOf(funcion.getId_butaca().getId_butaca()));
            jtFecha.setText(funcion.getFecha());
            jtHora_entrada.setText(funcion.getHora_entrada());
            jtHora_salida.setText(funcion.getHora_salida());
        }
    }//GEN-LAST:event_btBuscarActionPerformed
    
    public void cargarpelicula(){
    
        for(Pelicula item: listaPelicula ){
            jCBId_pelicula.addItem(String.valueOf(item.id_pelicula));
        }
    }
    
    public void cargarsala(){
    
        for(Sala item: listaSala ){
            jCBId_sala.addItem(String.valueOf(item.id_sala));
        }
    }
    
    public void cargarbutaca(){
    
        for(Butaca item: listaButaca ){
            jCBId_butaca.addItem(String.valueOf(item.id_butaca));
        }
    }
    
    public void tomardatos(){
        jtId_sala.setText((String) jCBId_sala.getSelectedItem());
        jtId_butaca.setText((String) jCBId_butaca.getSelectedItem());
        jtId_pelicula.setText((String) jCBId_pelicula.getSelectedItem());
    }
   
  
 
 public void BorrarFilaPelicula(){
    
        int a=modelo.getRowCount()-1;
        for( int i = a; i >=0; i-- ){
            modelo.removeRow(i);
        }
    }
  public void CargarDatosPelicula(){
    
        BorrarFilaPelicula();
        
        for (Pelicula c : listaPelicula){
            modelo.addRow(new Object[]{c.getId_pelicula(),c.getNombre(),c.getGenero(),c.getAnio()});
        } 
    }
  public void CabeceraTablaPelicula(){
      ArrayList<Object> columns = new ArrayList<Object>();
      columns.add("id_pelicula");
      columns.add("nombre");
      columns.add("genero");
      columns.add("anio");
       
      for(Object it: columns){
          modelo.addColumn(it);
      }
      tPelicula.setModel(modelo);
      
    }
  
  public void BorrarFilaSala(){
    
        int a=modelo1.getRowCount()-1;
        for( int i = a; i >=0; i-- ){
            modelo1.removeRow(i);
        }
    }
  public void CargarDatosSala(){
    
        BorrarFilaSala();
        
        for (Sala c : listaSala){
            modelo1.addRow(new Object[]{c.getId_sala(),c.getCant_butaca()});
        } 
    }
  public void CabeceraTablaSala(){
      ArrayList<Object> columns = new ArrayList<Object>();
      columns.add("id_sala");
      columns.add("Cant_Butaca");
       
      for(Object it: columns){
          modelo1.addColumn(it);
      }
      tSala.setModel(modelo1);
      
    }
  
    public void BorrarFilaButaca(){
    
        int a=modelo2.getRowCount()-1;
        for( int i = a; i >=0; i-- ){
            modelo2.removeRow(i);
        }
    }
  public void CargarDatosButaca(){
    
        BorrarFilaButaca();
        
        for (Butaca c : listaButaca){
            modelo2.addRow(new Object[]{c.getId_butaca(),c.getId_sala().getId_sala(),c.isEstado()});
        } 
    }
  public void CabeceraTablaButaca(){
      ArrayList<Object> columns = new ArrayList<Object>();
      columns.add("id_butaca");
      columns.add("id_sala");
      columns.add("estado");
       
      for(Object it: columns){
          modelo2.addColumn(it);
      }
      tButaca.setModel(modelo2);
      
    }
    public void BorrarFilaFuncion(){
    
        int a=modelo3.getRowCount()-1;
        for( int i = a; i >=0; i-- ){
            modelo3.removeRow(i);
        }
    }
  public void CargarDatosFuncion(){
    
        BorrarFilaFuncion();
        
        for (Funcion c : listaFuncion){
            modelo3.addRow(new Object[]{c.getId_funcion(),c.getId_pelicula().getId_pelicula(),c.getId_sala().getId_sala(),c.getId_butaca().getId_butaca(),c.getFecha(),c.getHora_entrada(),c.getHora_salida()});
        } 
    }
  public void CabeceraTablaFuncion(){
      ArrayList<Object> columns = new ArrayList<Object>();
      columns.add("id_funcion");
      columns.add("id_pelicula");
      columns.add("id_sala");
      columns.add("id_butaca");
      columns.add("fecha");
      columns.add("hora_entrada");
      columns.add("hora_salida");
       
      for(Object it: columns){
          modelo3.addColumn(it);
      }
      tFuncion.setModel(modelo3);
      
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btActualizar;
    private javax.swing.JButton btBorrar;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btGuardar;
    private javax.swing.JButton btLimpiar;
    private javax.swing.JComboBox<String> jCBId_butaca;
    private javax.swing.JComboBox<String> jCBId_pelicula;
    private javax.swing.JComboBox<String> jCBId_sala;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextField jtFecha;
    private javax.swing.JTextField jtHora_entrada;
    private javax.swing.JTextField jtHora_salida;
    private javax.swing.JTextField jtId;
    private javax.swing.JTextField jtId_butaca;
    private javax.swing.JTextField jtId_pelicula;
    private javax.swing.JTextField jtId_sala;
    private javax.swing.JTable tButaca;
    private javax.swing.JTable tFuncion;
    private javax.swing.JTable tPelicula;
    private javax.swing.JTable tSala;
    // End of variables declaration//GEN-END:variables
}
